<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GLTranslate.Abstractions\GLTranslate.Abstractions.csproj" />
    <ProjectReference Include="..\GLTranslate.Domain\GLTranslate.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GLTranslate.Providers.Google.Tests" />
  </ItemGroup>

</Project>
